export const data = [
  { name: "Mathematics & Statistics", color: "#7F77DD", sections: [
    { title: "Linear Algebra", tags: ["Vectors & matrices","Eigenvalues & eigenvectors","SVD","LU / QR / Cholesky decomposition","Dot product & cosine similarity","Matrix rank & null space","Orthogonality & projections","Determinants","Tensors & tensor operations","Frobenius norm"] },
    { title: "Calculus & Optimization", tags: ["Partial derivatives","Chain rule","Gradient & Hessian","Jacobian matrix","Taylor expansion","Convex vs non-convex functions","Lagrange multipliers","Saddle points","Constrained optimization","Numerical methods (Newton's, gradient descent variants)"] },
    { title: "Probability & Statistics", tags: ["Bayes' theorem","Conditional probability","MLE & MAP","Gaussian / Bernoulli / Poisson / Beta / Dirichlet distributions","Expectation, variance, covariance","Law of large numbers","Central limit theorem","Hypothesis testing & p-values","Confidence intervals","KL divergence","Jensen-Shannon divergence","Information theory & entropy","Monte Carlo methods","Markov chains"] },
  ]},
  { name: "Classical ML", color: "#1D9E75", sections: [
    { title: "Supervised Learning", tags: ["Linear regression","Logistic regression","SVM & kernel trick","Decision trees","Random forest","Gradient boosting (XGBoost, LightGBM, CatBoost)","k-NN","Naive Bayes","Ridge, Lasso, Elastic net","Isotonic regression"] },
    { title: "Unsupervised Learning", tags: ["k-Means","Hierarchical clustering","DBSCAN","HDBSCAN","PCA","t-SNE","UMAP","Gaussian Mixture Models","ICA","Sparse autoencoders","Anomaly detection (Isolation Forest, LOF)"] },
    { title: "Model Evaluation", tags: ["Bias-variance tradeoff","Cross-validation (k-fold, stratified, LOOCV, time-series split)","Accuracy, precision, recall, F1","ROC-AUC & PR-AUC","Confusion matrix","Log loss / cross-entropy","RMSE, MAE, MAPE","Calibration curves & Platt scaling","Imbalanced class handling (SMOTE, class weights, threshold tuning)","Multiple testing correction"] },
    { title: "Feature Engineering", tags: ["Feature selection (filter, wrapper, embedded)","Normalization & standardization","One-hot & ordinal encoding","Target encoding","Feature interaction & polynomial features","Imputation strategies","Dimensionality reduction","SHAP & permutation importance","Feature stores concept"] },
  ]},
  { name: "Deep Learning", color: "#D85A30", sections: [
    { title: "Fundamentals", tags: ["Backpropagation","Activation functions (ReLU, GELU, Swish, SiLU, Mish)","Weight initialization (Xavier, He, orthogonal)","Vanishing & exploding gradients","Batch / Layer / Group / RMS normalization","Dropout & DropPath","Universal approximation theorem","Inductive bias"] },
    { title: "Architectures", tags: ["MLP","CNN (ResNet, EfficientNet, ConvNeXt, DenseNet)","RNN / LSTM / GRU","Seq2Seq + attention","Transformer (encoder, decoder, encoder-decoder)","Vision Transformer (ViT, DeiT, Swin)","U-Net","GAN / VAE","Diffusion models","Graph Neural Networks (GCN, GAT, GraphSAGE)","Mixture of Experts (MoE)","State Space Models (Mamba, S4)","Hyena / RWKV","Perceiver / cross-attention architectures"] },
    { title: "Training Tricks", tags: ["SGD + momentum","Adam, AdaGrad, RMSProp, Lion","Learning rate schedules (cosine, warmup, cyclic, OneCycleLR)","Gradient clipping","Label smoothing","Mixup & CutMix","Stochastic depth","EMA of weights","Curriculum learning","Data-efficient training"] },
    { title: "Distributed Training", tags: ["Data parallelism (DDP)","Model parallelism (tensor, pipeline)","ZeRO (Stage 1/2/3)","FSDP","DeepSpeed","Megatron-LM","Gradient checkpointing","Mixed precision (fp16, bf16)","Activation checkpointing","AllReduce, AllGather collectives","Interleaved pipeline scheduling"] },
  ]},
  { name: "LLM Architecture & Training", color: "#185FA5", isNew: true, sections: [
    { title: "Transformer Internals", tags: ["Multi-head self-attention","Causal masking","Positional encoding (sinusoidal, RoPE, ALiBi, YaRN)","KV cache mechanics","Grouped Query Attention (GQA)","Multi-Query Attention (MQA)","Sliding window attention","Flash Attention 1/2/3","Sparse attention patterns","Cross-attention"] },
    { title: "Pretraining", tags: ["Next token prediction (CLM)","Masked Language Modeling (MLM)","Denoising objectives (T5-style)","MoE routing (top-k, expert capacity)","Scaling laws (Chinchilla, Kaplan)","Data deduplication & quality filtering","Tokenizer design (BPE, WordPiece, Unigram, SentencePiece)","Context length extension (RoPE scaling, YaRN, LongRoPE)","Long-context pretraining"] },
    { title: "Fine-tuning & Alignment", tags: ["Supervised Fine-Tuning (SFT)","Instruction tuning","Chat templates & special tokens","RLHF","DPO","ORPO","SimPO","IPO","KTO","Constitutional AI","RLAIF","Rejection sampling fine-tuning","Catastrophic forgetting","LoRA","QLoRA","DoRA","LoftQ","IA3","Adapter layers","Prefix tuning","Prompt tuning"] },
    { title: "Evaluation", tags: ["Perplexity","BLEU, ROUGE, METEOR","BERTScore","LLM-as-a-judge","MT-Bench","MMLU","HumanEval","GSM8K","MATH benchmark","Hallucination metrics","AlpacaEval","TruthfulQA"] },
  ]},
  { name: "LLM Inference & Serving", color: "#0F6E56", isNew: true, sections: [
    { title: "KV Cache", tags: ["KV cache mechanics (key/value storage per layer)","KV cache memory footprint formula","Paged attention (vLLM)","Prefix caching / prompt caching","KV cache quantization","Streaming KV offload to CPU/disk","Shared prefix KV cache","Radix tree-based KV cache (SGLang)","KV cache for MoE models","Multi-turn KV reuse"] },
    { title: "Quantization", tags: ["Post-training quantization (PTQ)","Quantization-aware training (QAT)","INT8 / INT4 / FP8","GPTQ","AWQ (Activation-aware Weight Quantization)","SmoothQuant","GGUF / llama.cpp formats","Weight-only vs activation quantization","Mixed precision quantization","KV cache quantization"] },
    { title: "Batching & Scheduling", tags: ["Static batching","Continuous batching","Dynamic batching","Chunked prefill","Prefill-decode disaggregation","Speculative decoding","Medusa heads","EAGLE speculative decoding","Lookahead decoding","Batch size vs latency vs throughput tradeoffs"] },
    { title: "Decoding Strategies", tags: ["Greedy decoding","Beam search","Top-k sampling","Top-p (nucleus) sampling","Min-p sampling","Temperature scaling","Repetition penalty","Constrained decoding (grammar-based, outlines, LMQL)","Structured output (JSON mode)","Logit bias"] },
    { title: "Inference Frameworks", tags: ["vLLM","TensorRT-LLM","SGLang","llama.cpp","Ollama","Triton Inference Server","TorchServe","ONNX Runtime","ExLlamaV2","MLC-LLM","Hugging Face TGI"] },
    { title: "Performance & Hardware", tags: ["GPU memory bandwidth vs compute bound","Roofline model for LLM inference","Tensor parallelism for inference","Time to first token (TTFT)","Time per output token (TPOT)","Throughput (tokens/sec)","SLO-aware serving","Flash Decoding","Tensor cores & CUDA kernels","Multi-instance GPU (MIG)"] },
  ]},
  { name: "AI Agents & Agentic Systems", color: "#993556", isNew: true, sections: [
    { title: "Agent Foundations", tags: ["ReAct (Reason + Act)","Chain-of-Thought (CoT)","Tree of Thoughts (ToT)","Self-consistency","Reflexion (self-critique loop)","Plan-and-execute","LATS (LLM-augmented tree search)","Scratchpad & inner monologue","Agent loop (observe → think → act)","Task decomposition"] },
    { title: "Tool Use & Function Calling", tags: ["Function calling (OpenAI spec)","Tool schemas (JSON Schema)","Parallel tool calls","Structured output for tools","Tool selection & routing","Code interpreter","Web search tool","Error handling & retry in tool loops"] },
    { title: "Memory Systems", tags: ["In-context memory (prompt window)","External memory (vector DB retrieval)","Episodic memory","Semantic memory","Procedural memory","Working memory management","Memory compression & summarization","Cross-session persistence","Mem0 / MemGPT patterns"] },
    { title: "Multi-Agent Systems", tags: ["Orchestrator-worker pattern","Hierarchical agents","Agent debate","Agent specialization & roles","Shared state management","Agent handoff","Parallelism across agents","Consensus & voting mechanisms","Agent evaluation & monitoring"] },
    { title: "Agent Protocols & Standards", tags: ["MCP (Model Context Protocol)","MCP server / client / host architecture","MCP tools, resources, prompts primitives","MCP transport (stdio, SSE, HTTP)","A2A (Agent-to-Agent Protocol)","A2A agent cards & capability discovery","A2A task lifecycle (submitted → working → completed)","AUI / AIUI (Agent User Interface)","OpenAI Assistants API","Anthropic tool use API"] },
    { title: "Agentic Frameworks", tags: ["LangChain / LangGraph","LlamaIndex","AutoGen (Microsoft)","CrewAI","Semantic Kernel","DSPy","Pydantic AI","Smolagents (HuggingFace)","OpenAI Swarm","Phidata"] },
    { title: "Safety & Reliability", tags: ["Prompt injection attacks","Indirect prompt injection","Tool call validation","Sandboxed code execution","Human-in-the-loop checkpoints","Agent guardrails","Loop detection & termination","Cost & token budget management","Observability & tracing (LangSmith, Langfuse, Arize)","Evals for agents"] },
  ]},
  { name: "RAG & Knowledge Systems", color: "#854F0B", isNew: true, sections: [
    { title: "Retrieval Fundamentals", tags: ["Dense retrieval (bi-encoder)","Sparse retrieval (BM25, TF-IDF)","Hybrid search (dense + sparse)","Reciprocal rank fusion (RRF)","Re-ranking (cross-encoder)","Late interaction (ColBERT)","Matryoshka embeddings","Binary & scalar embedding quantization","Embedding models (E5, BGE, GTE, Nomic)"] },
    { title: "RAG Architectures", tags: ["Naive RAG","Advanced RAG","Modular RAG","Corrective RAG (CRAG)","Self-RAG","HyDE (Hypothetical Document Embeddings)","Multi-query retrieval","Step-back prompting","RAG fusion","GraphRAG","Agentic RAG","Long-context RAG vs retrieval tradeoff"] },
    { title: "Chunking & Indexing", tags: ["Fixed-size chunking","Semantic chunking","Recursive character splitting","Document hierarchy chunking","Proposition-based chunking","Parent-child chunking","Sliding window chunks","Metadata filtering","Payload indexing","Incremental index updates"] },
    { title: "Vector Databases", tags: ["FAISS (Flat, IVF, HNSW)","Pinecone","Weaviate","Qdrant","Chroma","Milvus","PGVector","HNSW algorithm","IVF-PQ compression","ANN benchmarks","Namespace & tenant isolation"] },
  ]},
  { name: "NLP & Language Understanding", color: "#378ADD", sections: [
    { title: "Core NLP", tags: ["Tokenization","POS tagging","NER","Dependency parsing","Coreference resolution","Text classification","Sentiment analysis","Semantic similarity","Summarization","Translation","Question answering"] },
    { title: "Embeddings", tags: ["Word2Vec (CBOW, Skip-gram)","GloVe","FastText","Sentence-BERT","OpenAI text-embedding models","Instructor embeddings","Multilingual embeddings (LaBSE, mE5)","Embedding fine-tuning (contrastive, NLI)","Embedding evaluation (MTEB benchmark)"] },
    { title: "Key Models", tags: ["BERT","RoBERTa","DeBERTa","GPT family","T5 / mT5","BART","LLaMA / Llama 2 / Llama 3","Mistral / Mixtral","Gemma","Phi / Phi-3","Qwen","Claude / Gemini / Command R"] },
  ]},
  { name: "Computer Vision", color: "#D4537E", sections: [
    { title: "Core Tasks", tags: ["Image classification","Object detection (YOLO, Faster R-CNN, DETR, RT-DETR)","Semantic segmentation","Instance segmentation (Mask R-CNN, SAM)","Keypoint detection","Optical flow","Depth estimation","Video understanding","Image generation & super-resolution"] },
    { title: "Vision-Language", tags: ["CLIP","BLIP / BLIP-2","LLaVA","GPT-4V / GPT-4o","Qwen-VL","PaliGemma","Grounding DINO","DALL-E / Stable Diffusion","ControlNet"] },
    { title: "Techniques", tags: ["Transfer learning","Contrastive learning (SimCLR, MoCo, BYOL)","Data augmentation (Mixup, CutMix, RandAugment)","Feature pyramid networks","Non-maximum suppression","Grad-CAM"] },
  ]},
  { name: "MLOps & Production ML", color: "#BA7517", sections: [
    { title: "Experiment Management", tags: ["Experiment tracking (MLflow, W&B, Comet)","Model registry","Data versioning (DVC, LakeFS)","Reproducibility","Hyperparameter tuning (Optuna, Ray Tune, Bayesian optimization)","AutoML","Model cards"] },
    { title: "Deployment & Serving", tags: ["ONNX & TorchScript export","REST / gRPC serving","Batch vs real-time inference","A/B testing & shadow mode","Canary & blue-green deployments","Feature stores (Feast, Tecton)","Model monitoring","Data drift & concept drift detection","SLO / latency budgets"] },
    { title: "LLM-Specific Ops", tags: ["LLM gateway / proxy (LiteLLM, PortKey, Helicone)","Prompt versioning & management","Token cost tracking","Rate limiting & quota management","Semantic response caching","LLM observability (LangSmith, Arize Phoenix, Langfuse)","Eval pipelines for LLMs","Red teaming & safety testing pipelines"] },
    { title: "Infrastructure", tags: ["Docker & Kubernetes for ML","GPU cluster management","CUDA & driver versions","Spot/preemptible instance strategies","Cloud ML platforms (SageMaker, Vertex AI, AzureML)","Data pipelines (Airflow, Prefect, Dagster)","Stream processing (Kafka, Flink) for ML","Cost optimization","Checkpointing & fault tolerance"] },
  ]},
  { name: "Reinforcement Learning", color: "#639922", sections: [
    { title: "Core Concepts", tags: ["MDP (Markov Decision Process)","State, action, reward, policy","Value function & Q-function","Bellman equation","Exploration vs exploitation","ε-greedy, UCB, Thompson sampling","Reward shaping","Sparse vs dense rewards"] },
    { title: "Algorithms", tags: ["Q-Learning","Deep Q-Network (DQN)","Double DQN, Dueling DQN","Policy gradient (REINFORCE)","Actor-Critic (A2C, A3C)","PPO","SAC","DDPG","TD3","Model-based RL (Dreamer, MuZero)","Offline RL (CQL, IQL)"] },
    { title: "RL for LLMs", tags: ["RLHF pipeline","Reward model training","PPO for LLMs","DPO vs PPO tradeoffs","KL penalty constraint","Reward hacking","RLAIF","Process reward models (PRM)","Outcome reward models (ORM)","GRPO (Group Relative Policy Optimization)","Verifiable reward signals"] },
  ]},
  { name: "Responsible AI & Theory", color: "#888780", sections: [
    { title: "Explainability", tags: ["SHAP","LIME","Grad-CAM","Integrated gradients","Counterfactual explanations","Probing classifiers","Mechanistic interpretability","Superposition hypothesis","Sparse autoencoders for interpretability"] },
    { title: "Fairness & Security", tags: ["Sampling bias, label bias, measurement bias","Fairness metrics (demographic parity, equalized odds)","Adversarial examples & robustness","Jailbreaking & prompt injection","Backdoor attacks","Membership inference attacks","Differential privacy","Federated learning","LLM red teaming","Hallucination & grounding"] },
    { title: "Theory", tags: ["PAC learning","VC dimension","No free lunch theorem","Rademacher complexity","Double descent","Grokking","Neural tangent kernel (NTK)","Implicit regularization","Benign overfitting","Information bottleneck","Scaling laws"] },
  ]},
  { name: "Generative AI & Frontier", color: "#E8593C", sections: [
    { title: "Generative Models", tags: ["GANs (DCGAN, StyleGAN, CycleGAN)","VAE & beta-VAE","Normalizing flows","DDPM","DDIM","Score matching","Stable Diffusion / SDXL","Latent Diffusion Models (LDM)","Flow matching","Consistency models","DiT (Diffusion Transformer)"] },
    { title: "Multimodal", tags: ["Vision-language alignment (CLIP-style)","Text-to-image generation","Text-to-video (Sora, RunwayML)","Text-to-speech (TTS)","ASR (Whisper)","Cross-modal retrieval","Any-to-any models (GPT-4o, Gemini)","Multimodal embeddings"] },
    { title: "Frontier Topics", tags: ["Meta-learning (MAML, Prototypical Networks)","Few-shot & zero-shot learning","Self-supervised learning","Neural architecture search (NAS)","Implicit neural representations (NeRF)","State Space Models (Mamba)","Test-time compute scaling","Reasoning models (o1, DeepSeek-R1)","Thinking tokens / extended thinking","Long-horizon planning"] },
  ]},
];
